### ISSUE TITLE
Dock name while configuration

### ISSUE THREAD

**Issue by delihus** [open-navigation/opennav_docking#71]
Why the dock plugin instances are configured with a plugin name instead of dock name?
https://github.com/open-navigation/opennav_docking/blob/main/opennav_docking/src/dock_database.cpp#L159

**Comment by SteveMacenski** [comment]
This is the plugin database, not the dock instances ([here are the dock instances)](https://github.com/open-navigation/opennav_docking/blob/main/opennav_docking/src/dock_database.cpp#L186). We do this to allow for `N` instances to share `M` plugins so that we don't have 1,000 docks with dock plugins on RAM instead of 1,000 docks that are just a simple set of metadata with just the 4 types of docks (for example). The dock plugins are the thing that can be large or involve alot of traffic like subscribing to data or executing itself AI models.

**Comment by delihus** [comment]
Thank you for explanation!
